"""add_person_verification_columns

Revision ID: 4fdcd5d5c94e
Revises: 3f01d45130fe
Create Date: 2026-04-05 16:47:22.642247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdcd5d5c94e'
down_revision: Union[str, Sequence[str], None] = '3f01d45130fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('pending_verification', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('suggested_name', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('suggested_relation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'suggested_relation')
    op.drop_column('persons', 'suggested_name')
    op.drop_column('persons', 'pending_verification')
    # ### end Alembic commands ###
